try {
  throw new Error('oops')
} catch (err) {
  err
}
